import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import agenciesRouter from "./agencies";
import departmentsRouter from "./departments";
import positionsRouter from "./positions";
import jobsRouter from "./jobs";
import candidatesRouter from "./candidates";
import applicationsRouter from "./applications";
import employeesRouter from "./employees";
import contractsRouter from "./contracts";
import aiScoresRouter from "./ai_scores";
import dashboardRouter from "./dashboard";
import aiRouter from "./ai";
import usersRouter from "./users";
import storageRouter from "./storage";
import notificationsRouter from "./notifications";
import integrationsRouter from "./integrations";
import pdfRouter from "./pdf";
import auditLogRouter from "./audit-log";
import savedJobsRouter from "./saved-jobs";
import leaveRouter from "./leave";
import attendanceRouter from "./attendance";
import onboardingRouter from "./onboarding";
import offboardingRouter from "./offboarding";
import performanceRouter from "./performance";
import trainingRouter from "./training";
import benefitsRouter from "./benefits";
import housingRouter from "./housing";
import documentsRouter from "./documents";
import orgChartRouter from "./org-chart";
import reportsRouter from "./reports";
import workflowsRouter from "./workflows";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(agenciesRouter);
router.use(departmentsRouter);
router.use(positionsRouter);
router.use(jobsRouter);
router.use(candidatesRouter);
router.use(applicationsRouter);
router.use(employeesRouter);
router.use(contractsRouter);
router.use(aiScoresRouter);
router.use(dashboardRouter);
router.use(aiRouter);
router.use(storageRouter);
router.use(notificationsRouter);
router.use(integrationsRouter);
router.use(pdfRouter);
router.use(auditLogRouter);
router.use(savedJobsRouter);
router.use(leaveRouter);
router.use(attendanceRouter);
router.use(onboardingRouter);
router.use(offboardingRouter);
router.use(performanceRouter);
router.use(trainingRouter);
router.use(benefitsRouter);
router.use(housingRouter);
router.use(documentsRouter);
router.use(orgChartRouter);
router.use(reportsRouter);
router.use(workflowsRouter);

export default router;
