from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from pathlib import Path

OUT=Path(r"C:\nisithrportal\artifacts\hr-portal\public\NISIT-HR-Portal-Enterprise-End-to-End-Handbook.docx")
JOB=Path(r"C:\Users\Mukombo\AppData\Local\Temp\codex-clipboard-aa44cbeb-44d5-42be-bfc1-3e421b343723.png")
ORG=Path(r"C:\Users\Mukombo\AppData\Local\Temp\codex-clipboard-55ac8661-744a-48bd-af27-e922b7be5182.png")
NAVY=RGBColor(10,44,80); RED=RGBColor(207,23,54); MUTED=RGBColor(91,99,110)

def shade(c,x):
 p=c._tc.get_or_add_tcPr();e=OxmlElement('w:shd');e.set(qn('w:fill'),x);p.append(e)
def field(p,code):
 r=p.add_run();b=OxmlElement('w:fldChar');b.set(qn('w:fldCharType'),'begin');i=OxmlElement('w:instrText');i.set(qn('xml:space'),'preserve');i.text=code;s=OxmlElement('w:fldChar');s.set(qn('w:fldCharType'),'separate');e=OxmlElement('w:fldChar');e.set(qn('w:fldCharType'),'end');r._r.extend([b,i,s,e])
def setup():
 d=Document();sec=d.sections[0];sec.top_margin=Inches(.72);sec.bottom_margin=Inches(.72);sec.left_margin=sec.right_margin=Inches(.8)
 n=d.styles['Normal'];n.font.name='Aptos';n.font.size=Pt(10.5);n.font.color.rgb=RGBColor(44,49,55);n.paragraph_format.space_after=Pt(6)
 for nm,sz,col in [('Heading 1',18,NAVY),('Heading 2',13,NAVY),('Heading 3',11,RED)]:
  s=d.styles[nm];s.font.name='Aptos Display';s.font.size=Pt(sz);s.font.bold=True;s.font.color.rgb=col;s.paragraph_format.space_before=Pt(12);s.paragraph_format.space_after=Pt(6)
 f=sec.footer.paragraphs[0];f.alignment=WD_ALIGN_PARAGRAPH.CENTER;f.add_run('PNG NISIT HR Portal | Enterprise End-to-End Handbook | Page ');field(f,'PAGE')
 return d
def title(d,t,sub=''):
 p=d.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=p.add_run(t);r.font.size=Pt(26);r.font.bold=True;r.font.color.rgb=NAVY
 if sub:p=d.add_paragraph(sub);p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.runs[0].italic=True;p.runs[0].font.color.rgb=MUTED
def note(d,label,text):
 t=d.add_table(rows=1,cols=1);t.alignment=WD_TABLE_ALIGNMENT.CENTER;c=t.cell(0,0);shade(c,'EEF4FB');p=c.paragraphs[0];r=p.add_run(label+'  ');r.bold=True;r.font.color.rgb=NAVY;p.add_run(text)
def table(d,rows):
 t=d.add_table(rows=1,cols=2);t.style='Table Grid';t.alignment=WD_TABLE_ALIGNMENT.CENTER
 for c,x in zip(t.rows[0].cells,['Control point','What good looks like']):c.text=x;shade(c,'DCE9F7')
 for a,b in rows:c=t.add_row().cells;c[0].text=a;c[1].text=b
def workflow(d,steps):
 d.add_paragraph('Workflow at a glance','Heading 2')
 t=d.add_table(rows=1,cols=1);t.alignment=WD_TABLE_ALIGNMENT.CENTER;c=t.cell(0,0);shade(c,'F8E9EC')
 p=c.paragraphs[0];p.alignment=WD_ALIGN_PARAGRAPH.CENTER
 for i,step in enumerate(steps):
  r=p.add_run(f'{i+1}. {step}');r.bold=True;r.font.size=Pt(9);r.font.color.rgb=NAVY
  if i < len(steps)-1:
   a=p.add_run('  →  ');a.bold=True;a.font.size=Pt(13);a.font.color.rgb=RED
def chapter(d,no,name,purpose,steps,checks):
 d.add_paragraph(f'{no}. {name}','Heading 1');d.add_paragraph(purpose)
 workflow(d,steps)
 d.add_paragraph('Standard operating steps','Heading 2')
 # Fresh numbering instance per chapter: all procedures start at 1.
 style_num=d.styles['List Number']._element.pPr.numPr.numId.val
 numbering=d.part.numbering_part.element
 source=next(n for n in numbering.findall(qn('w:num')) if n.get(qn('w:numId'))==str(style_num))
 abstract=source.find(qn('w:abstractNumId')).get(qn('w:val'))
 existing=[int(n.get(qn('w:numId'))) for n in numbering.findall(qn('w:num')) if n.get(qn('w:numId')).isdigit()]
 fresh=str(max(existing)+1); num=OxmlElement('w:num');num.set(qn('w:numId'),fresh)
 abstract_el=OxmlElement('w:abstractNumId');abstract_el.set(qn('w:val'),abstract);num.append(abstract_el)
 override=OxmlElement('w:lvlOverride');override.set(qn('w:ilvl'),'0');start=OxmlElement('w:startOverride');start.set(qn('w:val'),'1');override.append(start);num.append(override);numbering.append(num)
 for x in steps:
  p=d.add_paragraph(x,style='List Number');ppr=p._p.get_or_add_pPr();numpr=OxmlElement('w:numPr');ilvl=OxmlElement('w:ilvl');ilvl.set(qn('w:val'),'0');numid=OxmlElement('w:numId');numid.set(qn('w:val'),fresh);numpr.extend([ilvl,numid]);ppr.append(numpr)
 d.add_paragraph('Quality, security and completion checks','Heading 2');table(d,checks)
 note(d,'Role note','Only actions permitted by the signed-in role are visible. If a menu item or action is missing, request access from the appropriate HR administrator rather than sharing accounts.')
 d.add_page_break()

d=setup();title(d,'PNG NISIT HR Portal','Enterprise End-to-End User Handbook | Staff, applicants, managers, HR and executives');d.add_paragraph('Version 1.0 | August 2026',style='Subtitle');note(d,'Purpose','This handbook is the authoritative operational companion for everyday use of the portal. It is written in clear language but uses enterprise controls: responsible roles, completion checks, data-quality rules and escalation paths.');d.add_page_break()
title(d,'Document control and how to use this handbook');table(d,[('Audience','Applicants/non-staff, employees, supervisors, hiring managers, HR officers, executives and system administrators.'),('Use','Read the role-specific chapters first, then use the workflow and troubleshooting chapters when completing work.'),('Evidence standard','Use only portal records and authorised documents. Do not use screenshots, exported files or verbal requests as a substitute for an approved record.'),('Support standard','When escalating an issue, provide the module, record reference, date/time, what you tried and a clean screenshot.')]);d.add_paragraph('Guide structure','Heading 2');d.add_paragraph('Parts I–II establish safe access and navigation. Parts III–VI cover applicant, employee, manager and HR workflows. Parts VII–VIII cover reporting, data protection, troubleshooting and appendices. Each chapter ends with a completion check.');d.add_page_break()
title(d,'Contents');
for line in ['Part I: Access, navigation and shared controls','Part II: Applicant and non-staff journey','Part III: Employee self-service','Part IV: Recruitment and manager journey','Part V: HR workforce lifecycle','Part VI: Executive, organisation and reporting','Part VII: Data, security and support','Part VIII: Appendices, checklists and glossary']:d.add_paragraph(line,style='List Bullet')
d.add_paragraph('The following 40 operating chapters are designed to be read independently when completing the associated task.');d.add_page_break()

chapters=[
('Portal orientation','The home experience presents a role-aware menu, a profile/welcome area and notifications. The same portal is used by different audiences, but permissions determine what each person can see and change.',['Sign in with your own account.','Confirm the welcome panel shows the correct name and email.','Open the navigation group needed for your task.','Use Help & User Guide when you need a role guide.'],[('Identity','The name and email match the signed-in user.'),('Navigation','Only use modules relevant to the current task.'),('Sign-out','Sign out when using a shared device.')]),
('Authentication and password recovery','Account protection is the first control in every workflow. A valid account is required before the portal can enforce permissions and show records.',['Enter your registered email and password.','If credentials are rejected, select Forgot password?','Use only the reset link sent to your own email.','Sign in again and verify the welcome panel.'],[('Password','Never share it or store it in a browser on public devices.'),('Lockout','Stop repeated attempts; use password recovery.'),('Access issue','Escalate to HR/IT with your email and time of attempt.')]),
('Profile, welcome panel and notifications','The welcome panel identifies the active user and the notification bell carries actionable reminders.',['Open My Account to review your profile.','Keep email and phone details current.','Open the notification bell at the beginning and end of a work session.','Follow notification links only after checking the record context.'],[('Identity','Use your legal/current name.'),('Notifications','Do not ignore approval or expiry alerts.'),('Privacy','Do not expose profile details on shared screens.')]),
('Navigation and role-based access','The sidebar is grouped so users can find work by purpose. Missing options are normally a permission decision, not a fault.',['Expand a group heading to reveal its modules.','Select the module label, not an unrelated dashboard card, for a full workflow.','Use My Profile for personal tools.','Request role access through the authorised user-management process.'],[('Least privilege','Do not use another person’s account.'),('Role clarity','Ask HR which role owns a blocked task.'),('Auditability','Use the assigned role for all changes.')]),
('Universal table controls','Operational tables use a consistent standard for discovery, selection and export.',['Use Search for a keyword.','Use Filters for field-specific search.','Select a heading to sort; select again to reverse sort.','Use Columns to show/hide/reset; resize columns where needed.','Use page controls, selection and Actions only after reviewing selected rows.','Export only the minimum authorised dataset.'],[('Filters','Clear filters before reporting an empty result.'),('Bulk actions','Confirm selection count and target status.'),('Exports','Store exports securely and delete local copies when no longer needed.')]),
('Job vacancy discovery','Applicants and staff can view publicly available vacancies.',['Open Job Vacancies.','Search by title, location, division or keyword.','Open the vacancy detail.','Confirm status and closing date before action.','Save a job only when you plan to return to it.'],[('Eligibility','Read required qualifications first.'),('Status','Open and Published vacancies are applicant-facing.'),('Closing date','Do not apply after the advertised close.')]),
('Job detail review','The job detail provides the authoritative vacancy description.',['Read role overview and responsibilities.','Review qualifications, skills, work arrangement and location.','Check required documents and salary visibility.','Use Share only when sharing an approved public vacancy.','Select Apply Now only after the review.'],[('Accuracy','Do not rely on a copied or outdated job description.'),('Documents','Prepare only documents requested.'),('Decision','Save the job if you need time before applying.')]),
]
for i,(n,p,st,ch) in enumerate(chapters,1):chapter(d,i,n,p,st,ch)
# clean screenshot divider
d.add_paragraph('Clean reference screen: vacancy detail','Heading 1');d.add_paragraph('This clean example shows a public vacancy with the Apply Now action. It intentionally excludes errors, warning banners and annotated marks.');
if JOB.exists():d.add_picture(str(JOB),width=Inches(6.4));d.add_paragraph('Figure 1. Vacancy detail reference screen.',style='Caption')
d.add_page_break()
more=[
('Applicant registration','External users register an applicant account before applying.',['Select Register as applicant.','Enter legal name, email and a strong password.','Verify information before submission.','Sign in and complete your account/profile when prompted.'],[('Email','Use an address you can access.'),('Name','Use official identity spelling.'),('Duplicate account','Do not create multiple accounts for the same person.')]),
('Applicant application wizard','The application wizard creates a structured application and should be completed deliberately.',['Select Apply Now.','Complete Personal, Contact and Availability sections.','Add Education, Experience, Skills and Languages.','Upload documents, answer screening questions and read declarations.','Submit only after final review.'],[('Draft','A saved draft is not a submitted application.'),('Required fields','Complete all required answers before proceeding.'),('Truthfulness','Enter information that can be verified.')]),
('Applicant document uploads','Documents form part of the application evidence record.',['Upload CV as PDF/DOC/DOCX up to 10 MB.','Select the correct type for extra documents.','Wait for the completed upload state.','Review file names before next step.'],[('File type','Use permitted formats only.'),('Size','Keep under 10 MB.'),('Failure','Keep the wizard open and follow the displayed message.')]),
('Applicant submission and tracking','Submission places the application in the recruitment workflow.',['Select Submit Application once.','Wait for confirmation.','Open My Applications.','Review status history and notifications.','Respond to requests by their due date.'],[('Duplicate prevention','Do not submit twice for the same vacancy.'),('Monitoring','Check portal and email regularly.'),('Withdrawal','Use the portal process if withdrawal is available.')]),
('Leave application','Leave requests must have a valid category, period and handover reason.',['Open Leave & Absence.','Select Apply for Leave.','Choose category and valid start/end dates.','Enter reason and handover.','Submit and monitor status.'],[('Dates','End date cannot precede start date.'),('Balance','Review entitlement where displayed.'),('Approval','Do not assume leave is approved until status says so.')]),
('Attendance clock','Attendance actions record work time and must be used honestly.',['Open Attendance Clock.','Clock in at the start of duty.','Clock out at the end.','Review entries and report corrections promptly.'],[('Ownership','Record your own time only unless authorised.'),('Accuracy','Do not backdate or invent time.'),('Correction','Use the authorised correction path.')]),
('Document vault and HR letters','Authorised documents are available in secure employee-service modules.',['Open Document Vault or HR Letters.','Search/filter to locate a record.','Use View Document from inside the portal.','Download only where permitted.'],[('Access','Do not attempt to access another person’s record.'),('Storage','Keep downloaded files secure.'),('Version','Use the latest signed/versioned document.')]),
('Recruitment workflow','Hiring users move applications through controlled stages.',['Open Applications or Recruitment Workflow.','Open candidate/application detail.','Review evidence and notes.','Move only to an appropriate next stage.','Record outcome and required communication.'],[('Fairness','Apply consistent criteria.'),('Stage history','Do not skip controls without reason.'),('Notes','Keep factual and professional.')]),
('Candidate review and shortlist','Shortlisting turns evaluation into an accountable decision.',['Review qualifications against the published criteria.','Check documents and screening answers.','Use shortlist/workflow tools permitted to your role.','Record selection rationale.'],[('Conflict','Declare conflicts of interest.'),('Evidence','Base decisions on application evidence.'),('Privacy','Do not export candidate information unnecessarily.')]),
('Interview and assessment','Assessment outcomes must be recorded consistently.',['Schedule through the approved process.','Use the agreed panel/rubric.','Record scores and notes promptly.','Update stage only after required approval.'],[('Consistency','Use the same criteria for comparable candidates.'),('Confidentiality','Limit notes to authorised reviewers.'),('Decision','Ensure score and recommendation align.')]),
('Offer and onboarding handoff','A successful candidate moves from recruitment to employment setup.',['Confirm approval for offer.','Record offer status and required documents.','Start onboarding workflow after acceptance.','Assign tasks and dates to owners.'],[('Separation of duties','Use appropriate approvals.'),('Dates','Use agreed start date.'),('Handoff','Do not mark onboarding complete before tasks close.')]),
('Employee master records','Employee records are the source for workforce and contract workflows.',['Open Employees and find the record.','Verify legal identity, contacts, department, position and supervisor.','Use an employable date of birth.','Save and verify the updated record.'],[('DOB','Never use a future or non-employable date.'),('Appointment','Use effective appointment date.'),('Status','Match personnel status to employment reality.')]),
('Onboarding workflow','Onboarding coordinates the first-day and pre-start controls.',['Create/select the employee workflow.','Assign each task to an accountable owner.','Set realistic due dates.','Upload evidence where required.','Monitor outstanding tasks to completion.'],[('Owner','Every task has one clear owner.'),('Due date','Avoid arbitrary past dates.'),('Completion','Only close with evidence where required.')]),
('Contract management','Contracts capture employment terms and expiry controls.',['Create/select the contract.','Choose contract type and applicable period.','Use an end date only for time-bound contracts.','Upload signed document/version through the portal.','Monitor expiry and renewal action.'],[('Permanent roles','Do not show non-applicable expiry dates.'),('Renewal','Act before the end date.'),('Signed evidence','Replace superseded signed versions clearly.')]),
('Offboarding and clearance','Offboarding protects people, assets, access and records at separation.',['Initiate workflow using confirmed separation details.','Assign IT, asset, finance and HR clearances.','Set realistic separation and due dates.','Track unresolved items.','Close only after required clearances.'],[('Access','Revoke at the approved time.'),('Assets','Record return evidence.'),('Finalisation','Do not close with missing mandatory clearances.')]),
('Organisation hierarchy','The organisation view maps positions, filled roles and vacancies.',['Open Org Hierarchy.','Use division and position filters.','Select cards for relevant roster detail.','Interpret filled/vacant totals with filters in mind.'],[('Headcount','Use approved position data.'),('Vacancy','Distinguish vacant positions from open job advertisements.'),('Print','Review current filters before printing.')]),
]
for j,(n,p,st,ch) in enumerate(more,len(chapters)+1):chapter(d,j,n,p,st,ch)
d.add_paragraph('Clean reference screen: organisation hierarchy','Heading 1');d.add_paragraph('This clean reference shows the organisational view, its headcount cards and available filters.');
if ORG.exists():d.add_picture(str(ORG),width=Inches(6.4));d.add_paragraph('Figure 2. Organisation hierarchy reference screen.',style='Caption')
d.add_page_break()
final=[
('Dashboard drilldowns','Dashboard cards and charts are starting points, not final evidence.',['Select a metric card or chart.','Review source records in the drilldown.','Apply filters where available.','Open the operational record before action.'],[('Evidence','Use source records for decisions.'),('Counts','Check filters and date scope.'),('Empty result','Confirm access and filters before escalation.')]),
('Standard reports and exports','Reports turn filtered operational data into controlled outputs.',['Open Standard Reports.','Select report and date range.','Apply only relevant filters.','Review rows before export.','Use CSV/TSV/JSON or Print as required.'],[('Period','Use a defensible reporting date range.'),('Export','Apply data classification rules.'),('Retention','Delete local copies when no longer needed.')]),
('Approval delegation and escalation','Delegation and escalation maintain timely decisions when approvers are unavailable.',['Confirm the delegated approver and authority.','Set an applicable start/end period.','Review escalated item context and evidence.','Approve, return or reject with a clear comment.'],[('Delegation','Do not delegate outside authority.'),('Dates','Use actual availability period.'),('Audit','Comments explain the decision.')]),
('User management overview','Administrators maintain access without bypassing accountability.',['Open User Management.','Search existing user before creating another.','Assign the correct role, agency and status.','Save and verify access outcome.'],[('Uniqueness','Avoid duplicate email accounts.'),('Role','Use least privilege.'),('Change log','Ensure the action is auditable.')]),
('Notifications and reminders','Notifications connect events to action.',['Review daily.','Open source record.','Complete/acknowledge the action.','Escalate if blocked.'],[('Timeliness','Act before due date.'),('Context','Never action from notification text alone.'),('History','Keep records current.')]),
('Data quality rules','Good data keeps dashboard, workflow and reports trustworthy.',['Use real names, dates and references.','Leave non-applicable fields blank rather than inventing data.','Correct detected errors promptly.','Check saved values after update.'],[('Dates','No future DOB; no expiry date for permanent contract.'),('Status','Reflect actual workflow state.'),('Duplicates','Search before creating records.')]),
('Security and privacy','Personnel information requires careful handling.',['Use your own account only.','Lock/sign out from shared devices.','Export minimum data.','Store documents only in approved locations.','Report suspected unauthorised access immediately.'],[('Credentials','Never share token/password.'),('Documents','Use authorised recipients only.'),('Incident','Preserve details for support.')]),
('Troubleshooting and support','A good support request allows rapid diagnosis.',['Read the exact message.','Confirm connectivity and refresh once after saving work.','Retry only when safe.','Capture clean screenshot.','Report module, record ID, time and steps.'],[('Do not','Repeatedly submit forms or create duplicates.'),('Screenshot','Exclude sensitive content when possible.'),('Escalation','Use HR/IT support channel.')]),
('Glossary and final checklist','Common terms help users communicate precisely.',['Review the glossary when unsure of status or workflow term.','Use the final checklist before completing high-impact work.','Return to Help & User Guide for role-specific manuals.'],[('Applicant','External user applying for a vacancy.'),('Workflow','Controlled sequence of tasks/stages.'),('Audit trail','Recorded history of accountable actions.')]),
('Role-to-module reference','This reference helps users identify the normal owner of a task before creating a request or escalating an issue.',['Confirm whether you are acting as applicant, employee, manager, HR officer, executive or administrator.','Open the module associated with the task.','If a control is unavailable, request an authorised role review.'],[('Applicants','Jobs, My Applications, My Account.'),('Employees','Employee services and own profile.'),('Managers/HR','Recruitment and assigned workforce workflows.')]),
('Date and status reference','Dates and statuses are used by dashboards, alerts, reports and workflow decisions.',['Use a date of birth that reflects an employable adult.','Use appointment, contract and separation dates from approved records.','Use contract expiry/renewal dates only for time-bound contracts.','Confirm status before reporting counts.'],[('Permanent employment','No artificial expiry date.'),('Renewal','New period begins only after approved renewal.'),('Closed workflow','All mandatory steps completed.')]),
('Document and version reference','Documents should remain traceable from upload through replacement.',['Name supporting files clearly before upload.','Upload the signed/current version through its associated workflow.','Replace superseded versions only when authorised.','Use portal viewing links, not unverified external URLs.'],[('Current version','Clearly identifiable and authorised.'),('Retention','Follow NISIT retention policy.'),('Access','Restricted to permitted users.')]),
('Export and print reference','Exports are operational records and need the same care as portal screens.',['Filter to the smallest necessary dataset.','Review columns before exporting.','Use the appropriate format for the receiving process.','Store only in approved locations.','Remove local copies when work is complete.'],[('CSV/TSV','Structured spreadsheet processing.'),('JSON','System/data integration use.'),('Print','Review current filters and page range first.')]),
('Escalation reference','Escalation is used when work cannot proceed safely or in time.',['Document the issue and impacted record.','State what action has already been attempted.','Attach a clean, non-sensitive screenshot where useful.','Send to the designated HR/IT owner.','Keep the workflow open until the outcome is confirmed.'],[('Urgent','Access, separation, payroll or security impact.'),('Normal','Data correction or usability question.'),('Evidence','Time, module, record reference and steps.')]),
]
for k,(n,p,st,ch) in enumerate(final,len(chapters)+len(more)+1):chapter(d,k,n,p,st,ch)
d.add_paragraph('Enterprise completion checklist','Heading 1');bullets=['Correct user and role confirmed','Correct module and record selected','All applicable dates logical and complete','Supporting documents uploaded/verified where required','Status and comments accurately reflect the action','Sensitive data handled according to policy','Outcome saved and verified']
for x in bullets:d.add_paragraph('☐ '+x)
note(d,'Next document','The separate Administrator Technical Guide will cover configuration, integrations, security administration, API operations, database/seed procedures and technical troubleshooting.');OUT.parent.mkdir(parents=True,exist_ok=True);d.save(OUT);print(OUT)
